### ISSUE TITLE
UndefinedCalledMethodPrecondition

### ISSUE THREAD

**Issue by YuyanBao** [OpenJML/OpenJML#444] opened 2016-05-28 17:04 UTC
Hi,

I got an error "UndefinedCalledMethodPrecondition", which means that "Calling a method whose composite precondition is not true is not allowed in a JML expression. ". But  Relaxed.diffIndex(pat, a)   does not have a precondition.

The code is shown below.
`
public class Relaxed {

```
//@ requires true;
//@ ensures pat.length == 0 ==> \result == true;
//@ ensures a.length == 0  && pat.length == 1 ==> \result == true; 
//@ ensures a.length == 0  && pat.length > 1 ==> \result == false; 
//@ ensures pat.length > 0 && a.length > 0 ==>  Relaxed.diffIndex(pat, a) == pat.length ==> \result == true;
 public static boolean isRelaxedPrefix(int[] pat, int[] a) {
    int shift = 0;
    int index = 0;

    if (pat.length == 0) return true;
    if (a.length == 0 && pat.length == 1) return true;
    if (a.length == 0 && pat.length > 1) return false;
    assert a.length > 0 && pat.length > 0;
    if (Relaxed.diffIndex(pat, a) == pat.length) return true;
    //@ maintaining 0 <= index && index <= pat.length;
    //@ maintaining 0 <= index - shift && index - shift <= a.length && 0 <= shift && shift <= 1;
   //@ maintaining  Relaxed.diffIndex(pat, a) > index ==>(\forall int i; 0 <= i && i < index; pat[i] == a[i]) ;
   //@ maintaining  Relaxed.diffIndex(pat, a) >  index ==> (\forall int j; Relaxed.diffIndex(pat, a) < j && j < index; pat[j] == a[j - 1]);
   //@ decreases pat.length - index - shift;
    while((pat.length > index ) && (a.length > index - shift)){
        if (pat[index] != a[index - shift]){
            if (shift == 0) shift = 1;
            else return false;
        }

         index = index + 1;

    }
    if (a.length == index - shift && pat.length > index ) return false;
    return true;
}


//@ requires true;
//@ ensures 0 <= \result && \result <= pat.length; 
//@ ensures (\forall int i; 0 <= i && i < \result; pat[i] == a[i]);
//@ ensures (pat.length > \result) && (a.length > \result) ==> pat[\result] != a[\result];
public /*@ pure @*/ static int diffIndex(int[] pat, int[] a)
{
  int index = 0;
  //@ maintaining 0 <= index && index <= pat.length && index <= a.length;
  //@ maintaining (\forall int i; 0 <= i && i < index; pat[i] == a[i]);
  //@ decreases pat.length - index;
  while((pat.length > index) && (a.length > index))
  {
      if(pat[index] == a[index]){
        index = index + 1;
      } else {
        return index;
      }

  }
  return index;
}
```

}

`

Error message:
/tmp/tmpAQBG_M/Relaxed.java:8: warning: The prover cannot establish an assertion (UndefinedCalledMethodPrecondition: /tmp/tmpAQBG_M/Relaxed.java:41: ) in method isRelaxedPrefix //@ ensures pat.length > 0 && a.length > 0 ==> Relaxed.diffIndex(pat, a) == pat.length ==> \result == true;

**Comment by iconmaster5326** [comment] 2016-08-23 16:01
This is not a bug, from what I can tell- In OpenJML, arguments are (by default) non-null. This adds a precondition for the arguments to not be null. Therefore, your function DOES have a precondition that is not \true. Either changing the default nullity to nullable or adding the nullable modifier to your arguments fixes your issue.

@davidcok : Can you confirm this is the correct behavior of OpenJML, and if so, close this issue?

**Comment by davidcok** [comment] 2017-03-14 02:35
The reported issue is fixed. So closing this report. The tests themselves are gitbug444 and gitbug444a (or variations thereof), which still show some other difficulties, which will be fixed separately.

**Closed by davidcok** 2017-03-14 02:35 UTC
Labels: OpenJML
