### ISSUE TITLE
Internal JML bug, java.lang.NullPointerException - Java 9 issue

### ISSUE THREAD

**Issue by Jankoekenpan** [OpenJML/OpenJML#591] opened 2017-11-21 15:40 UTC
java -jar openjml.jar ./C.java

`Unrecognized version: 9
Internal JML bug - please report.  BuildOpenJML-0.8.24-20171007
java.lang.NullPointerException
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:149)
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:134)
        at com.sun.tools.javac.file.Locations.access$0(Locations.java:133)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:617)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:643)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:577)
        at com.sun.tools.javac.file.Locations.getLocation(Locations.java:678)
        at com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
        at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2758)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)
        at com.sun.tools.javac.jvm.ClassReader.access$0(ClassReader.java:2429)
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
        at com.sun.tools.javac.comp.JmlEnter.visitTopLevel(JmlEnter.java:217)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at org.jmlspecs.openjml.JmlTree$JmlCompilationUnit.accept(JmlTree.java:889)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:258)
        at com.sun.tools.javac.comp.JmlEnter.classEnter(JmlEnter.java:469)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:486)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.comp.JmlEnter.main(JmlEnter.java:774)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:992)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.main.Main.compile(Main.java:410)
        at org.jmlspecs.openjml.Main.compile(Main.java:560)
        at com.sun.tools.javac.main.Main.compile(Main.java:399)
        at com.sun.tools.javac.main.Main.compile(Main.java:390)
        at org.jmlspecs.openjml.Main.execute(Main.java:396)
        at org.jmlspecs.openjml.Main.execute(Main.java:354)
        at org.jmlspecs.openjml.Main.execute(Main.java:341)
        at org.jmlspecs.openjml.Main.main(Main.java:313)`

C.java:

`public class C {

	//@ public invariant next >= 0;
	private /*@ spec_public @*/ int[] indices;
	private /*@ spec_public @*/ int next;

	/*@ public behavior
    @ ensures \result == (\forall int x; (\forall int y; 0 <= x && x < y && y < a.length; a[x] <= a[y]));
    @ assignable \nothing;
    @ pure public static model boolean isSorted(int[] a);
	 */

	/*@ public normal_behavior
    @ ensures next == 0 && this.indices == indices;
    @ assignable next, this.indices;
    @*/
	public C(int[] indices) {
		this.indices = indices;
		next = 0;
	}

	/*@ public normal_behavior
    @   requires isSorted(a);
    @   ensures ((\exists int x; 0 <= x && x < a.length; a[x] == v) ?  \result >= 0 && \result < a.length && a[\result] == v : \result == -1);
    @	  assignable \nothing;
    @*/
	public static /*@ pure @*/ int search(int[] a, int v) {
		int l = 0;
		int r = a.length - 1;

		if (a.length == 0) { 
			return -1;
		} else if (a.length == 1) { 
			return a[0] == v ? 0 : -1;
		}

		/*@ loop_invariant 0 <= l && l < r && r < a.length
        @                && (\forall int x; 0 <= x && x < l; a[x] < v)
        @                && (\forall int x; r < x && x < a.length; v < a[x]);
        @ decreases r - l;
        @*/
		while(r > l + 1) {
			int mid = l + (r - l) / 2;
			if(a[mid] == v) {
				return mid;
			} else if(a[mid] > v) {
				r = mid;
			} else {
				l = mid;
			}
		}

		if(a[l] == v) return l;
		if(a[r] == v) return r;

		return -1;
	}

	/*@ public normal_behavior
    @ requires isSorted(a) && a != indices;
    @ requires next < indices.length;
    @ ensures (\exists int i; i>=0 && i<a.length; a[i] == v) ? indices[\old(next)] == \result : (next == \old(next) && indices[next] == \old(indices[next]));  
    @ ensures (\exists int i; i>=0 && i<a.length; a[i] == v) ? a[\result] == v  : \result == -1;
    @ assignable indices[next], next;
    @ */
	public int addIndex(int[] a, int v) {
		int idx = search(a,v);
		if (idx >= 0) {
			indices[next] = idx;
			next++;
		}  
		return idx;
	}

	/*@ 
  	@ public exceptional_behavior
  	@ requires isSorted(a);
  	@ requires next >= indices.length;
  	@ requires  (\exists int i; i>=0 && i<a.length; a[i] == v);
  	@ signals (ArrayIndexOutOfBoundsException) true;
  	@ assignable \nothing;
  	@*/
	public int addIndex2(int[] a, int v) {
		int idx = search(a,v);
		if (idx >= 0) {
			indices[next] = idx;
			next++;
		}  
		return idx;
	}

}`

The `Unrecognised version: 9` is probably caused by a method that parses the java version, [the version-string scheme got changed in jdk9](http://openjdk.java.net/jeps/223).

**Comment by davidcok** [comment] 2017-11-21 15:45
OpenJM does not (yet) support JDK9 -  though it should not crash as you show here.
Thanks,
- David

**Comment by davidcok** [comment] 2018-01-10 21:42
Not reproduced. Try again with Java 9.

**Comment by Jankoekenpan** [comment] 2018-01-11 11:04
Same error:
```
C:\Users\Jan\Studie\workspace\Examples-OpenJML\src\xyz\janboerman\bachref\openjml>java -jar "C:\users\jan\studie\jml\tools\openjml-0.8.24-20171007\openjml.jar" ./C.java -esc -exec C:\users\jan\studie\jml\tools\z3\z3-4.3.2-x64-win\bin\z3.exe
Unrecognized version: 9.0.1
Internal JML bug - please report.  BuildOpenJML-0.8.24-20171007
java.lang.NullPointerException
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:149)
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:134)
        at com.sun.tools.javac.file.Locations.access$0(Locations.java:133)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:617)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:643)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:577)
        at com.sun.tools.javac.file.Locations.getLocation(Locations.java:678)
        at com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
        at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2758)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)
        at com.sun.tools.javac.jvm.ClassReader.access$0(ClassReader.java:2429)
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
        at com.sun.tools.javac.comp.JmlEnter.visitTopLevel(JmlEnter.java:217)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at org.jmlspecs.openjml.JmlTree$JmlCompilationUnit.accept(JmlTree.java:889)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:258)
        at com.sun.tools.javac.comp.JmlEnter.classEnter(JmlEnter.java:469)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:486)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.comp.JmlEnter.main(JmlEnter.java:774)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:992)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.main.Main.compile(Main.java:410)
        at org.jmlspecs.openjml.Main.compile(Main.java:560)
        at com.sun.tools.javac.main.Main.compile(Main.java:399)
        at com.sun.tools.javac.main.Main.compile(Main.java:390)
        at org.jmlspecs.openjml.Main.execute(Main.java:396)
        at org.jmlspecs.openjml.Main.execute(Main.java:354)
        at org.jmlspecs.openjml.Main.execute(Main.java:341)
        at org.jmlspecs.openjml.Main.main(Main.java:313)
```

**Comment by davidcok** [comment] 2018-01-11 13:32
Have you installed Java 9 on your system?

**Comment by Jankoekenpan** [comment] 2018-01-11 13:40
Yup, `java -version` prints:
```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by snowball77** [comment] 2018-08-23 02:47
I get the same issue with OpenJML, Eclipse Photon and Java 10.0.2

**Comment by davidcok** [comment] 2018-08-23 05:51
OpenJML will not work with Java 9 until it is explicitly merged with OpenJDK 9. This is planned but not started yet.

**Comment by snowball77** [comment] 2018-08-23 06:43
I understand and I fully agree. However, the situation is more subtle. Eclipse runs under JDK 10 in my case as it is the system default VM (which is very hard to change under MacOS). The program I am developing is configured to compile and run against java 8. Hence I expected it to work. However, the openjml GUI runs openjml from the VM eclipse is using instead of the project’s VM. Hence, I end up having this error popping up all the time in the UI.

—-
Steffen Becker
University of Stuttgart, Reliable Software Systems

Am 23.08.2018 um 07:51 schrieb David Cok <notifications@github.com<mailto:notifications@github.com>>:

OpenJML will not work with Java 9 until it is explicitly merged with OpenJDK 9. This is planned but not started yet.

**Comment by davidcok** [comment] 2018-08-23 08:47
Thanks for the clarification

**Comment by davidcok** [comment] 2024-02-15 19:23
This problem is fixed on OpenJML21, and the submitted code is a test case.
It does have some verification failures because the specs are not quite correct.
Closing as resolved.

**Closed by davidcok** 2024-02-15 19:23 UTC
Labels: OpenJML
