### ISSUE TITLE
Catastrophic JML internal error due to InputStream.jml

### ISSUE THREAD

**Issue by stasiran** [OpenJML/OpenJML#469] opened 2016-09-20 20:43 UTC
While verifying the following file with -esc,

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class Repro {

    public static class Bar {
        private static final FileInputStream URANDOM;

        static {
            FileInputStream tmp = null;
            try {
                tmp = new FileInputStream("/dev/urandom");
            } catch (FileNotFoundException e) {
                tmp = null;
            }
            URANDOM = tmp;
        }

        
        private static synchronized void getSeed(int length) {
            int read = 0;
            byte[] result = new byte[length];
            try {
		URANDOM.read(result, read, length-read);
            } catch (final IOException ex) {
                throw new RuntimeException(ex);
            }
        }
    }
}

I get the following error: (specs17/java/io/InputStream.jml):159: error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
                     b[i] == \old(inputBytes[i-off+(int)readPosition]));
                                                   ^
  Reason: Unimplemented case combination

**Comment by davidcok** [comment] 2016-09-24 01:42
Two problems: The catastrophic error was caused by an attempt to check assignable permission in an initializer block. This no longer crashes, though the check of permission to assign must still be implemented.

The second problem (not shown) above was a failure to establish an invariant of an Exception, caused by missing assumptions regrading the invariants of the parameter of a catch block.

Both fixed in commit c1e74e9cf7b99ebd951bff142b680f0ba7067315

**Comment by davidcok** [comment] 2016-09-24 11:36
Additional commit needed: 622f79d083047e9bd34fcc77849b86af15974c00

**Closed by davidcok** 2016-09-24 11:36 UTC
