### ISSUE TITLE
Recursion again?

### ISSUE THREAD

**Issue by pys** [OpenJML/OpenJML#572] opened 2017-10-04 14:02 UTC
[Perhaps reopening #559, #566  ?]

Dear David,

For a recursive factorial, I obtain the error messages below when running "Typecheck JML"
from Eclipse neon.3 using the latest version (BuildOpenJML-20170930).

Thanks in advance for any help,

---
public class fact {

	/*@requires n >= 0
	 *@ensures \result == (\product int i; 0 < i && i <= n; i) 
	 */
	public static /*@ pure @*/ int fac(int n) {
		if(n<=1)
			return 1;
		else
			return n*fac(n-1);
			
	}
}

---
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
[0,00] Executing openjml on fact.java
Internal JML bug - please report.  BuildOpenJML-20170930
java.lang.NullPointerException
	at com.sun.tools.javac.parser.JavacParser.term3(JavacParser.java:1225)
	at com.sun.tools.javac.parser.JmlParser.term3(JmlParser.java:2994)
	at com.sun.tools.javac.parser.JmlParser.term2Rest(JmlParser.java:3399)
	at com.sun.tools.javac.parser.JavacParser.term2(JavacParser.java:913)
	at com.sun.tools.javac.parser.JmlParser.term2Imp(JmlParser.java:2693)
	at com.sun.tools.javac.parser.JmlParser.term2Equiv(JmlParser.java:2670)
	at com.sun.tools.javac.parser.JmlParser.term1(JmlParser.java:2656)
	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:837)
	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:817)
	at com.sun.tools.javac.parser.JavacParser.parseExpression(JavacParser.java:780)
	at com.sun.tools.javac.parser.JmlParser.parsePredicateOrNotSpecified(JmlParser.java:2042)
	at com.sun.tools.javac.parser.JmlParser.parseExprClause(JmlParser.java:2056)
	at com.sun.tools.javac.parser.JmlParser.getClause(JmlParser.java:1955)
	at com.sun.tools.javac.parser.JmlParser.parseSpecificationCase(JmlParser.java:1835)
	at com.sun.tools.javac.parser.JmlParser.parseMethodSpecs(JmlParser.java:1707)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBodyDeclaration(JmlParser.java:1070)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3559)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceBody(JmlParser.java:381)
	at com.sun.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3408)
	at com.sun.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3349)
	at com.sun.tools.javac.parser.JmlParser.classOrInterfaceOrEnumDeclaration(JmlParser.java:315)
	at com.sun.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3338)
	at com.sun.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3278)
	at com.sun.tools.javac.parser.JmlParser.parseCompilationUnit(JmlParser.java:192)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:633)
	at org.jmlspecs.openjml.JmlCompiler.parse(JmlCompiler.java:124)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:670)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:960)
	at org.jmlspecs.openjml.JmlCompiler.parseFiles(JmlCompiler.java:244)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:864)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:560)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.executeNS(Main.java:486)
	at org.jmlspecs.openjml.API.execute(API.java:215)
	at org.jmlspecs.openjml.eclipse.OpenJMLInterface.executeExternalCommand(OpenJMLInterface.java:283)
	at org.jmlspecs.openjml.eclipse.Utils$1.run(Utils.java:283)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
ENDING with exit code 4
INTERNAL ERROR: return code = 4   Command: -command=check -strictJML=false -purityCheck=true -show=false -verboseness= -nullableByDefault=false -no-internalSpecs -specspath /Users/pys/Documents/workspace4.4/Spojcoins/src:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/904/0/.cp/java8:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/904/0/.cp/java7:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/904/0/.cp/java6:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/904/0/.cp/java5:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/904/0/.cp/java4 -sourcepath /Users/pys/Documents/workspace4.4/Spojcoins/src -no-internalRuntime -classpath /Users/pys/Documents/workspace4.4/Spojcoins/src:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/JObjC.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/Users/pys/.p2/pool/plugins/org.junit_4.12.0.v201504281640/junit.jar:/Users/pys/.p2/pool/plugins/org.hamcrest.core_1.3.0.v201303031735.jar:/Applications/eclipse/modeling-neon/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/903/0/.cp/jmlruntime.jar /Users/pys/Documents/workspace4.4/Spojcoins/src/fact.java 

[0,00] Executing openjml on fact.java

**Comment by davidcok** [comment] 2017-10-04 14:18
Pierre-Yves:

1) You have a couple of syntax errors. The crash is being caused by the spurious * in *@ensures. It should not crash of course on any input, but the workaround here is easy - delete the *
2) Then the parser will tell you that you need semicolons at the end of the requires and ensures expressions
3) I would also advise a space after the @ and before the keywords. In some circumstances that can kook like a Java annotation.

4) With all that, however, you will get a message that \product is not yet supported in the SMT engine (nor are \sum, \numof \max \min). They are coming, as I need them myself, but you should use a different example for now.

- David

**Comment by davidcok** [comment] 2017-10-08 02:21
Fixed in V0.8.24

**Closed by davidcok** 2017-10-08 02:21 UTC
Labels: OpenJML
