### ISSUE TITLE
Problem in Running JML Source code within Eclipse

### ISSUE THREAD

**Issue by IjazAhmed** [OpenJML/OpenJML#728] opened 2021-05-02 11:58 UTC
I fetched JML  source code by following the instructions mentioned at 
https://github.com/OpenJML/OpenJML/wiki/OpenJML-Development-Environment-Setup

I opened the repositories in Eclipse.  I executed the "/OpenJMLUI/src/org/jmlspecs/openjml/eclipse/Activator.java" as an "Eclipse Application". It executed successfully and launch a new Eclipse application that includes all JML commands such as "Type Checker" and " Static Check (ESC)". However when I type-checks a JML annotated file. I got below error in the console of the newly launched Eclipse Application. 

[0.00] Executing openjml on MyTest.java
Fatal Error: Unable to find package org.jmlspecs.lang
ENDING with exit code 3

**Any idea, how can I fix this error.** 

Actually, my goal is to add some security-related contracts in JML.

**Comment by davidcok** [comment] 2021-05-05 23:17
I cannot reproduce this error, though for me also the IDE in the development environment is not working correctly.
You might also try installing the released version rather than trying the development environment.

In the meantime, use the command-line version as released.

- David

**Comment by davidcok** [comment] 2024-02-15 19:12
The Eclipse IDE is no longer supported. It may be again in the future, but not real soon -- and when it is, it will be on a new code base.
So I'm closing this issue.

**Closed by davidcok** 2024-02-15 19:12 UTC
