### ISSUE TITLE
\bigint-related error in RAC compiler

### ISSUE THREAD

**Issue by robsimmons** [OpenJML/OpenJML#532] opened 2017-08-17 01:04 UTC
Code in hello.java

```
class Hello {
    //@requires (\bigint) i * (\bigint) j * (\bigint) k < (\bigint) Integer.MAX_VALUE;
    static int safe_mult(int i, int j, int k) {
	return i * j * k;
    }

    public static void main(String[] args) {
	System.out.println("Hello, world");
	System.out.println(safe_mult(1, 5, 6));
	System.out.println(safe_mult(1000000, 6, 8));
	System.out.println(safe_mult(1000000, 1000, 1000));
    }
}
```

Expected: the same thing I get from this snippet. Namely, compiles and runs and the third call to safe_mult has a precondition failure.

```
    //@requires i * j * k < Integer.MAX_VALUE;
    static /*@ spec_bigint_math @*/ int safe_mult(int i, int j, int k) {
	return i * j * k;
    }
```

Actual output:
```
whitewater:fiddle robs$ java -jar $OJ/openjml.jar -compile hello.java -rac
Internal JML bug - please report.  BuildOpenJML-0.8.18-20170726
java.lang.AssertionError: typecode NONE
	at com.sun.tools.javac.jvm.Code.typecode(Code.java:248)
	at com.sun.tools.javac.jvm.Code.newLocal(Code.java:2202)
	at com.sun.tools.javac.jvm.Code.newLocal(Code.java:2206)
	at com.sun.tools.javac.jvm.Gen.visitVarDef(Gen.java:1139)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
	at org.jmlspecs.openjml.JmlTree$JmlVariableDecl.accept(JmlTree.java:1286)
<snip>
```

**Comment by davidcok** [comment] 2017-08-17 03:24
Thanks for the report.
The problem is the explicit cast to \bigint.  That problem is fixed; the fix will be in V0.8.20 (next release).

Note though that you can leave the casts out and the program reports the errors. That is because by default the Java code is evaluated in safe mode (checks for overflows) and the specifications are evaluated in unbounded precision mode.

- David

**Closed** 2017-08-17 04:45 UTC
Labels: OpenJML

**Comment by pys** [comment] 2018-10-01 14:03
Dear David,

About your last sentence : I read in the JML manual (of 2013-05-31) that 'The mode spec_java_math is the default math used in specifications' (and a fortiori in code, we can assume). Am I reading an outdated version of the JML manual?

**Comment by davidcok** [comment] 2018-10-01 16:56
That is outdated.  Inn specs it is specs_bigint_math ; I code it is code_safe_math
